# Site settings
title: Different Games Conference 2016
description: > # this means to ignore newlines until "baseurl:"
  Different Games Conference is an annual student and volunteer-lead conference
  on diversity and inclusivity in games.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://2016.differentgames.org" # the base hostname & protocol for your site
twitter_username: differentgames
tumblr_username: differentgamescollective

# Build settings
markdown: kramdown
exclude:
  - vendor
  - deploy.sh
  - README.md
  - circle.yml
  - Gemfile
  - Gemfile.lock

collections:
  talks:
    output: true
  nav_pages:
    output: true
  sessions:
  games:
    output: true
    permalink: /arcade/:path/
  sponsors:
